image: maven:3.9.6-eclipse-temurin-21

stages:
  - build
  - test

build_api_service:
  stage: build
  script:
   - cd api-service
   - chmod +x mvnw
   - ./mvnw clean package

test_api_service:
  stage: test
  script:
    - cd api-service
    - chmod +x mvnw
    - ./mvnw test

build_notifier_service:
  stage: build
  script:
    - cd notifier-service
    - chmod +x mvnw
    - ./mvnw clean package

test_notifier_service:
  stage: test
  script:
    - cd notifier-service
    - chmod +x mvnw
    - ./mvnw test